name: Tests for Spring Boot
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    container:
      image: exoplatform/jdk:openjdk-21-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Cache ChromeDriver
        uses: actions/cache@v4
        with:
          path: ~/.cache/selenium
          key: ${{ runner.os }}-chromedriver-${{ hashFiles('**/build.gradle') }}
      - name: Setup Chrome
        run: |
          apt-get update
          apt-get install -y google-chrome-stable
      - name: Test with Gradle
        # Модульные и selenium тесты
        run: bash ./gradlew build test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always()  # Всегда запускать, даже если тесты упали
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          check_name: 'JUnit Test Report'
        # Нагрузочные тесты
      - name: Build and Run Spring Boot in background
        run: |
          bash ./gradlew bootRun &
          echo "App is starting..."
      - name: Wait for Spring Boot to be ready
        run: |
          timeout 180s bash -c 'until curl -s localhost:8080/actuator/health | grep "UP"; do sleep 5; done'
          echo "App is UP and running!"
      - name: Run Gatling Tests
        run: bash ./gradlew gatlingRun
