steps:
  - uses: actions/checkout@v4
  - name: Set up JDK 21 for x64
    uses: actions/setup-java@v4
    with:
      java-version: '21'
      distribution: 'temurin'
      architecture: x64
  - name: Test with Gradle
    run: ./gradlew test
