name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
      image: exoplatform/jdk:openjdk-21-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      #- name: Set up JDK 21 for x64
      #  uses: actions/setup-java@v4
      #  with:
      #    java-version: '21'
      #    distribution: 'temurin'
      #    architecture: x64
      - name: Test with Gradle
        run: bash ./gradlew test
