name: Tests for Spring Boot
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Tests:
    runs-on: ubuntu-latest
    container:
      image: exoplatform/jdk:openjdk-21-ubuntu-2204
    steps:
      - uses: actions/checkout@v4
      - name: Test with Gradle
        # Модульные тесты
        run: bash ./gradlew test
      - name: Build and Run Spring Boot in background
        # Используем & для запуска в фоне и nohup, чтобы процесс не убило сразу
        run: |
          bash ./gradlew bootRun &
          echo "App is starting..."
      - name: Wait for Spring Boot to be ready
        # Ожидаем ответа 200 от Actuator или главной страницы
        run: |
          timeout 180s bash -c 'until curl -s localhost:8080/actuator/health | grep "UP"; do sleep 5; done'
          echo "App is UP and running!"
          
      - name: Run Gatling Tests
        run: bash ./gradlew gatlingRun
